# GitHub Pages Deployment Workflow
#
# This workflow automatically deploys the application to GitHub Pages when:
# 1. Any commit is pushed to the master branch
# 2. The workflow is manually triggered from the GitHub Actions tab
#
# HOW TO USE:
# - For automatic deployment: Just push to the master branch
#
# - For manual deployment:
#   1. Go to Actions tab in GitHub repository
#   2. Select "Deploy to GitHub Pages" workflow
#   3. Click "Run workflow"
#   4. Optionally provide a custom WebSocket host URL
#   5. Click the green "Run workflow" button
#
# ENVIRONMENT VARIABLES:
# - VITE_WS_HOST: WebSocket host URL used during build
#   Default: '129.159.159.241'
#   Can be overridden when manually triggering the workflow
#
# WORKFLOW DETAILS:
# - Uses Bun for installing dependencies and building
# - Deploys the 'dist' directory to the 'gh-pages' branch
# - Only runs on commits to the master branch
# - Ignores changes to markdown files and .gitignore

name: Deploy to GitHub Pages

on:
    push:
        branches:
            - master
        paths-ignore:
            - "**.md"
            - ".gitignore"
    workflow_dispatch:
        inputs:
            ws_host:
                description: "WebSocket Host URL"
                required: false
                default: "129.159.159.241"
                type: string

# Add permissions needed for GitHub Pages deployment
permissions:
    contents: write
    pages: write
    id-token: write

env:
    VITE_WS_HOST: ${{ github.event.inputs.ws_host || '129.159.159.241' }}
    NODE_ENV: "production"

jobs:
    # Build and deploy on every push to master
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install

            - name: Debug Environment Variables
              run: |
                  echo "NODE_ENV: $NODE_ENV"
                  echo "VITE_WS_HOST: $VITE_WS_HOST"
                  echo "All environment variables:"
                  env | sort

            - name: Build
              run: bun run build --mode production
              env:
                  VITE_WS_HOST: ${{ env.VITE_WS_HOST }}
                  NODE_ENV: ${{ env.NODE_ENV }}

            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: dist
                  branch: gh-pages
                  clean: true